name: sqflitetoonline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  sqflite:
  path_provider:
  http:
  connectivity_plus: ^6.1.0
  internet_connection_checker_plus: ^2.5.2
  flutter_easyloading:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
